name: Unit tests and coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Vitest unit tests and push to coveralls
    
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Setup node ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"
    - name: Install dependencies and coveralls
      run: |
        pnpm install coveralls
    - name: Run unit tests and save coverage
      run: CI=true pnpm run test:coverage
    - name: Coveralls
      uses: coverallsapp/github-action@main
